jobs:
  run-install:
    uses: ./.github/workflows/install.yml  # Path to the install file

  run-tests:
    needs: pull-and-install
    runs-on: ubuntu-latest
    steps:
      - name: Run Sysbench Tests
        run: |
	          sudo sed -i '/require("oltp_common")/a sysbench.hooks.report_intermediate = sysbench.report_json' /usr/share/sysbench/oltp_read_write.lua
	          /usr/bin/sysbench   --mysql-host='127.0.0.1'   --mysql-port=3306   --mysql-db=sysbench   --mysql-user='tester2'   --mysql-password='.userMDS00'   --tables=3   --table_size=10000   oltp_common prepare
	          sleep 5
	          /usr/bin/sysbench  --mysql-host='127.0.0.1' --mysql-port=3306 --mysql-db=sysbench  --mysql-user='tester2'  --mysql-password='.userMDS00' --tables=3 --table_size=10000 --threads=3   --time=10 --report-interval=1  oltp_read_write run
